# Permalinks
permalink:           pretty

# Setup
title:               SensLog
tagline:             "Blog of super elegant noble Sage"
url:                 http://senscho.github.io
# paginate:            2
baseurl:             "/blog"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jihyun Cho
  url:               https://twitter.com/sens-cho
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/senscho

# menu items
navbar:
  - text: Home
    url: 
  - text: Posts
    url: posts
  - text: Tags
    url: tags
  - text: CV
    url: 
    align: right
  - text: Twit
    url: https://twitter.com/sens_cho
    align: right
    linktype: absolute
  - text: Likn
    url: https://www.linkedin.com/in/eecho
    align: right
    linktype: absolute
  - text: Git
    url: https://github.com/senscho
    align: right
    linktype: absolute

excerpt_separator: "<!-- more -->"  # default is \n\n. not liquid friendly

defaults:
  -
    # scope:
    #   path: ""
    #   type: "pages"
    values:
      use_math: true
      hide_code: false  

# Gems
Plugins:
  # - jekyll-paginate
  # - jekyll-gist

exclude:
  - README.md
  - run_jekyll.sh
  - LICENSE.md
  - "*.py"
  - "*.sh"
  - "_ipynbs/*"

